make:
	gcc ejercicio2_1.s -o ejercicio2_1
	gcc ejercicio2_2.s -o ejercicio2_2
	gcc ejercicio2_3.s -o ejercicio2_3
	gcc ejercicio2_4.s -o ejercicio2_4
clean:
	rm ejercicio2_1 ejercicio2_2 ejercicio2_3 ejercicio2_4
