make:
	as teclado.s -o teclado.o
	ld teclado.o -o teclado
	as greet.s -o greet.o
	ld greet.o -o greet
	as hanoi.s -o hanoi.o
	gcc hanoi.o -o hanoi
	as hanoi2.s -o hanoi2.o
	gcc hanoi2.o -o hanoi2
	as delay.s -o delay.o
	gcc delay.o -o delay
	as primos.s -o primos.o
	ld primos.o -o primos
	as stack.s -o stack.o
	gcc stack.o -o stack
clean:
	rm teclado.o teclado greet.o greet hanoi.o hanoi hanoi2.o hanoi2 delay.o delay primos.o primos stack.o stack

